import type { Memory, Collection } from './types'

export const mockMemories: Memory[] = [
  {
    id: 'mem-1',
    type: 'voice',
    title: 'Startup idea — Fintech for Artisans',
    content: 'Was walking downtown and had an idea for a platform that connects artisans with micro-lending. Key differentiator would be the integration with digital wallets in emerging markets. Could partner with local co-ops for distribution.',
    tags: ['#startup', '#fintech', '#ideas'],
    createdAt: '2025-01-15T14:32:00Z',
    aiSummary: 'A startup concept for artisan-focused fintech with micro-lending and digital wallet integration. Targets emerging markets through local co-op partnerships.',
    collectionId: 'col-1',
  },
  {
    id: 'mem-2',
    type: 'link',
    title: 'The Future of AI in Personal Knowledge Management',
    content: 'Great article on how AI is transforming how we capture and retrieve information. Key insight: the shift from keyword search to semantic understanding changes everything about personal knowledge tools.',
    tags: ['#ai', '#productivity', '#reading'],
    createdAt: '2025-01-15T10:15:00Z',
    source: 'https://example.com/ai-knowledge-mgmt',
    aiSummary: 'Article discussing the paradigm shift from keyword-based to semantic search in personal knowledge management tools, enabled by AI.',
    collectionId: 'col-2',
  },
  {
    id: 'mem-3',
    type: 'text',
    title: 'Book recommendation from Sarah',
    content: 'Sarah recommended "Thinking, Fast and Slow" by Daniel Kahneman. She said it completely changed how she thinks about decision-making. Should read the chapters on cognitive biases first.',
    tags: ['#books', '#recommendations', '#reading'],
    createdAt: '2025-01-14T18:45:00Z',
    aiSummary: 'A book recommendation for "Thinking, Fast and Slow" by Kahneman, focusing on cognitive biases. Recommended by Sarah.',
    collectionId: 'col-5',
  },
  {
    id: 'mem-4',
    type: 'image',
    title: 'Whiteboard notes from product meeting',
    content: 'Captured whiteboard with product roadmap for Q2. Three main tracks: Onboarding improvements, AI search enhancements, and mobile app launch. Key dates: Feb 15 for onboarding, March 1 for AI search, April 1 for mobile.',
    tags: ['#work', '#product', '#meetings'],
    createdAt: '2025-01-14T15:20:00Z',
    aiSummary: 'Product roadmap notes from Q2 planning meeting with three tracks: onboarding (Feb 15), AI search (March 1), mobile app (April 1).',
    collectionId: 'col-1',
  },
  {
    id: 'mem-5',
    type: 'voice',
    title: 'Recipe — Grandma\'s lemon pasta',
    content: 'Grandma\'s famous lemon pasta recipe: Cook spaghetti al dente. Sauce: 2 lemons juiced, 1 cup heavy cream, 1/2 cup parmesan, fresh basil, salt and pepper. Toss hot pasta with sauce, top with more parmesan and basil.',
    tags: ['#recipes', '#cooking', '#family'],
    createdAt: '2025-01-13T19:30:00Z',
    aiSummary: 'A family recipe for lemon pasta with cream sauce, parmesan, and fresh basil — recorded from grandmother.',
    collectionId: 'col-6',
  },
  {
    id: 'mem-6',
    type: 'link',
    title: 'Best coffee shops in San Francisco — 2025 guide',
    content: 'Comprehensive guide to SF coffee scene. Top picks: The Mill (Mission), Four Barrel (Valencia), Ritual (Hayes Valley), Blue Bottle (WFI). Each rated on atmosphere, wifi, and coffee quality.',
    tags: ['#coffee', '#travel', '#sanfrancisco'],
    createdAt: '2025-01-13T11:00:00Z',
    source: 'https://example.com/sf-coffee-guide',
    aiSummary: 'A curated guide to San Francisco\'s best coffee shops, including The Mill, Four Barrel, Ritual, and Blue Bottle with ratings.',
    collectionId: 'col-3',
  },
  {
    id: 'mem-7',
    type: 'text',
    title: 'Travel packing list for NYC trip',
    content: 'NYC trip Feb 10-14. Pack: warm coat, scarf, gloves, 2 business outfits, casual clothes, walking shoes, laptop + charger, notebook, toiletries. Flight: UA 456 departs 8:15 AM. Hotel: The Standard, East Village.',
    tags: ['#travel', '#nyc', '#planning'],
    createdAt: '2025-01-12T20:10:00Z',
    aiSummary: 'Packing list and travel details for a NYC trip February 10-14. Staying at The Standard, East Village.',
    collectionId: 'col-3',
  },
  {
    id: 'mem-8',
    type: 'image',
    title: 'Inspirational quote from museum visit',
    content: 'Photo of a quote at the SFMOMA: "The only way to do great work is to love what you do." — Sometimes you need a reminder. This resonated deeply with where I am right now in my career.',
    tags: ['#inspiration', '#quotes', '#personal'],
    createdAt: '2025-01-12T14:45:00Z',
    aiSummary: 'An inspirational quote photographed at SFMOMA about loving your work, reflecting on career direction.',
    collectionId: 'col-6',
  },
  {
    id: 'mem-9',
    type: 'text',
    title: 'Meeting notes — Design review with team',
    content: 'Design review feedback: Dashboard layout approved with minor changes. Need to increase card padding, adjust font hierarchy, and add empty states. Alex will handle the sidebar redesign. Next review: Friday 3pm.',
    tags: ['#work', '#design', '#meetings'],
    createdAt: '2025-01-11T16:00:00Z',
    aiSummary: 'Design review meeting notes: dashboard approved with tweaks. Alex on sidebar redesign. Follow-up Friday 3pm.',
    collectionId: 'col-1',
  },
  {
    id: 'mem-10',
    type: 'voice',
    title: 'Late night thought about memory architecture',
    content: 'Just realized that the way we structure memories in the app should mirror how the brain actually works — not folders and files, but associations and context. What if we built a graph-based view where memories are nodes and tags are edges? That would be a game changer.',
    tags: ['#ideas', '#product', '#architecture'],
    createdAt: '2025-01-11T23:45:00Z',
    aiSummary: 'A late-night insight about building a graph-based memory view where memories are nodes connected by tag-based edges, mirroring brain association patterns.',
    collectionId: 'col-2',
  },
]

export const mockCollections: Collection[] = [
  { id: 'col-1', name: 'Work', icon: 'briefcase', memoryCount: 24, lastUpdated: '2025-01-15', color: '#9D8BA7' },
  { id: 'col-2', name: 'Ideas', icon: 'lightbulb', memoryCount: 18, lastUpdated: '2025-01-14', color: '#E8B87A' },
  { id: 'col-3', name: 'Travel', icon: 'plane', memoryCount: 12, lastUpdated: '2025-01-13', color: '#7AB8B8' },
  { id: 'col-4', name: 'Books', icon: 'book-open', memoryCount: 9, lastUpdated: '2025-01-10', color: '#B87A7A' },
  { id: 'col-5', name: 'Recipes', icon: 'chef-hat', memoryCount: 15, lastUpdated: '2025-01-12', color: '#7AB87A' },
  { id: 'col-6', name: 'Personal', icon: 'moon', memoryCount: 21, lastUpdated: '2025-01-15', color: '#8B7AB8' },
]

export const allTags = [
  { name: '#work', count: 8 },
  { name: '#ideas', count: 6 },
  { name: '#startup', count: 4 },
  { name: '#travel', count: 5 },
  { name: '#books', count: 3 },
  { name: '#recipes', count: 3 },
  { name: '#productivity', count: 4 },
  { name: '#ai', count: 5 },
  { name: '#personal', count: 6 },
  { name: '#coffee', count: 2 },
  { name: '#design', count: 3 },
  { name: '#meetings', count: 3 },
  { name: '#fintech', count: 2 },
  { name: '#reading', count: 3 },
  { name: '#nyc', count: 2 },
  { name: '#cooking', count: 2 },
  { name: '#inspiration', count: 2 },
  { name: '#architecture', count: 2 },
  { name: '#sanfrancisco', count: 3 },
  { name: '#planning', count: 2 },
]

export const mockAiResponses: Record<string, { answer: string; sources: number; referencedIds: string[] }> = {
  'ideas': {
    answer: 'You saved 3 ideas this week. The most prominent one was about a "Fintech for Artisans" platform with micro-lending integration — you recorded it as a voice note on Wednesday. You also had a late-night insight about building a graph-based memory view for the app, and you saved a link about AI in knowledge management.',
    sources: 3,
    referencedIds: ['mem-1', 'mem-2', 'mem-10'],
  },
  'book': {
    answer: 'Sarah recommended "Thinking, Fast and Slow" by Daniel Kahneman. You saved this on January 14th. She specifically mentioned the chapters on cognitive biases as the most impactful. You also bookmarked an article about AI in personal knowledge management that references similar decision-making themes.',
    sources: 2,
    referencedIds: ['mem-3', 'mem-2'],
  },
  'travel': {
    answer: 'You have 3 travel-related memories. Your NYC trip is planned for February 10-14 — you\'re staying at The Standard in East Village with a flight on UA 456 at 8:15 AM. You also saved a guide to the best coffee shops in San Francisco, and you captured a photo of an inspirational quote at SFMOMA.',
    sources: 3,
    referencedIds: ['mem-7', 'mem-6', 'mem-8'],
  },
  'default': {
    answer: 'I searched through your memories and found some relevant connections. Based on what you\'ve saved recently, you seem to be focused on startup ideas and productivity tools. Your most recent captures include thoughts on fintech, design meeting notes, and some travel planning for NYC.',
    sources: 4,
    referencedIds: ['mem-1', 'mem-9', 'mem-7', 'mem-10'],
  },
}
